name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Build (release)
        run: cargo build --locked --release
      - name: Clippy
        run: cargo clippy --all-targets -- -W clippy::all
      - name: Test
        run: cargo test --locked
